
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Extracts menu items from an image of a menu, using an S3 URL.
 *
 * - extractMenuItems - A function that handles the extraction of menu items from an image URL.
 * - ExtractMenuItemsInput - The input type for the extractMenuItems function.
 * - ExtractMenuItemsOutput - The return type for the extractMenuItems function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtractMenuItemsInputSchema = z.object({
  menuImageUrl: z
    .string()
    .url()
    .describe(
      "An S3 URL pointing to the menu image after it has been uploaded."
    ),
});
export type ExtractMenuItemsInput = z.infer<typeof ExtractMenuItemsInputSchema>;

const ExtractMenuItemsOutputSchema = z.object({
  menuItems: z
    .array(
      z.object({
        name: z.string().describe('The name of the menu item.'),
        description: z.string().describe('The description of the menu item.'),
        price: z.string().describe('The price of the menu item.'),
      })
    )
    .describe('The extracted menu items.'),
});
export type ExtractMenuItemsOutput = z.infer<typeof ExtractMenuItemsOutputSchema>;

export async function extractMenuItems(input: ExtractMenuItemsInput): Promise<ExtractMenuItemsOutput> {
  return extractMenuItemsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'extractMenuItemsPrompt',
  input: {schema: ExtractMenuItemsInputSchema},
  output: {schema: ExtractMenuItemsOutputSchema},
  prompt: `You are an expert in extracting menu items from images of menus. Extract the menu items from the following image.

Menu Image URL: {{media url=menuImageUrl}}

Make sure to extract the name, description, and price of each menu item. If the image is unclear or not a menu, return an empty list of menu items.`,
});

const extractMenuItemsFlow = ai.defineFlow(
  {
    name: 'extractMenuItemsFlow',
    inputSchema: ExtractMenuItemsInputSchema,
    outputSchema: ExtractMenuItemsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

