import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { QueryClientProvider } from "@/lib/query-provider";
import { AuthProvider } from "@/contexts/AuthContext";
import { HelpButton } from "@/components/layout/HelpButton";
import { ClarityAnalytics } from "@/components/analytics/ClarityAnalytics";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clarity Menu",
  description: "AI-Powered Digital Menus and Marketing",
};

const faviconDataUri = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAA16SURBVHhe7Z1t ExtlGcD5t6169atW3ft1q1b12u0aKFFG21o0RdaNmgQ3aQxJjE0ISaNSRM0aTQkTUxC05A0QRNCEiZp0jRpEiZpEmPaJm0aNGnTpMmQNG3SpEmTJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3T3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3S3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3SpEmSJG3-aAAAABJRU5ErkJggg==";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={faviconDataUri} type="image/png" />
      </head>
      <body
        className={`${inter.variable} antialiased flex flex-col min-h-screen`}
      >
        <ClarityAnalytics />
        <QueryClientProvider>
          <AuthProvider>
            <div className="flex-grow">{children}</div>
            <Toaster />
          </AuthProvider>
        </QueryClientProvider>
        <HelpButton />
      </body>
    </html>
  );
}
